using CollaborativeTaskManager.EntityFrameworkCore;
using Xunit;

namespace CollaborativeTaskManager.EntityFrameworkCore;

public class CollaborativeTaskManagerEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<CollaborativeTaskManagerEntityFrameworkCoreFixture>
{

}
