using Volo.Abp;

namespace CollaborativeTaskManager.EntityFrameworkCore;

public abstract class CollaborativeTaskManagerEntityFrameworkCoreTestBase : CollaborativeTaskManagerTestBase<CollaborativeTaskManagerEntityFrameworkCoreTestModule>
{

}
